### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by hferentschik** [hferentschik/balena-weather#12]
Improve the README and add more information about the actual assembly/build part. 

The README just refers to https://projects.raspberrypi.org/en/projects/build-your-own-weather-station as a reference, without further information. The relevant portions of the build should be inlined into the README/repo (preferably with some images).

Maybe it even makes sense to extract the "build" part into a dedicated markdown file. This will keep the README a bit more concise.

High levels goals:

- Better descriptions of the concrete parts used
- Step by step build instructions 
- Important steps to watch out for

**Comment by mpous** [comment]
Just made a PR @hferentschik :)
